### ISSUE TITLE
Ability to change base href

### ISSUE THREAD

**Issue by ReindertKorver** [erickzanardo/flutter-gh-pages#5]
Hi,
Flutter has the default base href set to / in the head tag:
```html
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    Fore more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
	<base href="/">
...
```
So when I used your action to deploy using the gh-pages branch - on a different repo then ...github.io - the app threw errors because it couldn't find its assets because it was going to the root /, while it was running on ...github.io/reponame/.
I had to copy your yml into mine and run a python script to replace the `<base href="/">` with `<base href="/reponame/">`.
It works but would be nice if there was support in this Github action, are you able to add some property to specify the base href, and run a script which will do this for us? Or maybe there is some other way to accomplish it, with some command.

The python script I made:
```py
import sys
arg=sys.argv[1]
lines=[]
file= sys.argv[2]
with open(file, 'r') as f:
    lines = f.readlines()
    for i in range(len(lines)):
        if("<base href=\"/\">" in lines[i]):
            lines[i]="\t<base href=\"/"+str(arg)+"\">\n"
            break
print(lines)
with open(file, 'w') as f:
    for i in range(len(lines)):
        f.write(lines[i])
       
```
Running it is very simple with an extra step: 
`run: python ./.github/workflows/change_href.py ${{ format( '{0}/', github.event.repository.name) }} "./build/web/index.html"`

There might be a much better way, but this is what I could come up with.

**Comment by erickzanardo** [comment]
Hey, thanks for filling this very complete issue.

I am unsure if we should somehow automatic change that, the base href could be hard to predict, specially when a custom domain is used. Does that makes sense or am I missing something?

**Comment by ReindertKorver** [comment]
It isn't really predicting I think. The default is always no change, so it stays how it is now.
I found something [added base-href command in web](https://github.com/flutter/flutter/pull/80519), I don't know if this has been added yet, if not this feature is for later.
So if the property is specified, change the `flutter build web` command
I was thinking more like this:
```yml
...
      - uses: erickzanardo/flutter-gh-pages@v3
        with:
          workingDir: example
          rootDir: 'whatever/'
```
With this you change your `action.yml` to:
```yml
inputs:
  rootDir:
    description: 'The directory where the build will be hosted, like /project/'
    required: false
    default: /
...
runs:
  using: 'composite'
  steps:
...
    - run: flutter build web --release --web-renderer=${{inputs.webRenderer}} --base-href ${{inputs.rootDir}}  <--- the change
      shell: bash
      working-directory: ${{inputs.workingDir}}
```
You probably know better how to yml, but I think you'll get what I mean its just an extra option in the command.
